stages:
  - test

cache:
  paths:
     - .gradle
     - $GRADLE_USER_HOME

test:
  stage: test
  image: openjdk:12
  artifacts:
    paths:
      - service/build/libs/thermometer-service.jar
  before_script:
    - java --version
    - pwd
    - echo $GRADLE_USER_HOME
  script:
    - cd service
    - ./gradlew sonarqube -Dsonar.login=$SONARCLOUD_LOGIN -Dsonar.projectVersion=$CI_COMMIT_SHORT_SHA
